mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += static('node_modules', document_root=settings.BASE_DIR + '/node_modules')

mysite/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^add/$', views.edit, name='add'),
    url(r'^edit/(\d+)/$', views.edit, name='edit'),
    url(r'^delete_post/(\d+)/$', views.delete_post, name='delete')
]

mysite/polls/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=1000)
    date_of_publication = models.DateField()
    def __str__(self):
        return self.text

mysite/polls/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)
        widgets = {
            'text': forms.Textarea,
        }

mysite/polls/views.py
import datetime
from django.http import HttpResponse, Http404
from django.template import RequestContext, loader
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.core.urlresolvers import reverse

from .models import Post
from .forms import PostForm


def index(request):
    latest_text_list = Post.objects.order_by('date_of_publication')[:10]
    template = loader.get_template('polls/index.html')
    #output = ' '.join(p.text for p in latest_text_list)
    context = RequestContext(request, {
        'latest_text_list': latest_text_list,
    })
    return HttpResponse(template.render(context))

def detail(request, text_id):
    post = get_object_or_404(Post, pk=text_id)
    return render(request, 'polls/detail.html',{'post':post})



def edit(request, obj_id=None):
    post = None
    if obj_id:
        post = get_object_or_404(Post, pk=obj_id)

    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.date_of_publication = datetime.datetime.now()
        post.save()
        return redirect(reverse('polls:detail', args=(post.id, )))

    context = {
       'form': form
    }
    return render(request, 'polls/edit.html', context)


def delete_post(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    return redirect('/polls/')

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
</head>
<body>
    <div class="container">
    <div class="page-header">
        <h1>Detail information</h1>
    </div>
    <p><strong>Title: </strong>{{ post.title }}</p>
    <p><strong>Date of publication: </strong>{{ post.date_of_publication }}</p>
    <p><strong>Text: </strong>{{ post.text }}</p>
        <form action="/polls/edit/{{ post.id }}/">
       <!-- <form action="/polls/edit/"> -->
            <button type="submit" class="btn btn-success"> EDIT </button>
        </form>
         <p></p>
        <form action="{% url 'polls:delete' post.id %}">
         <button type="submit" class="btn btn-danger"> DELETE </button>
        </form>
    </div>
</body>
</html>

mysite/polls/templates/polls/edit.html
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-success">SAVE</button>
</form>

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
{% if latest_text_list %}
    <head>
        <link href="/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
    </head>
    <body>
    <div class="container">
    <div class="page-header">
        <h1>Posts</h1>
    </div>
        <table class="table">
            <tr>
                <th>id</th>
                <th>Title</th>
                <th>Date</th>
            </tr>
            {% for text in latest_text_list %}
                <tr>
                    <td>{{ text.id }}</td>
                    <td><a href="{% url 'polls:detail' text.id %}">{{ text.title }}</a></td>
                    <td>{{ text.date_of_publication }}</td>
                </tr>
            {% endfor %}
        </table>
        <a  href="{% url 'polls:add' %}" class="btn btn-success">Add post</a>
    </div>
    </body>
{% endif %}
</html>